# Generated by Django 3.2.11 on 2022-02-03 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220119_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 8', regex='^.{8}$')])),
                ('cpassword', models.CharField(max_length=30)),
            ],
        ),
    ]
